// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhdkmxwtsmwmbazqcvqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oZGtteHd0c213bWJhenFjdnFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NzMyNTMsImV4cCI6MjA2NzU0OTI1M30.QDYCwhq0Txj7kWPyFwrAAaAptKK374Zgjsv6LCzJJnY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});